### ISSUE TITLE
Pull request to upstream?

### ISSUE THREAD

**Issue by chris001** [mwennrich/milter-greylist-geoip2#2] opened 2020-07-12 16:18 UTC
It would be very good if the upstream package were able to read from both the old format GeoIP databases, and the new format GeoIP databases.  

Any plan to do a pull request to upstream with these changes?

**Comment by mwennrich** [comment] 2020-07-13 05:55
The problem is, there is - as far as I know - no "upstream git repository" of milter-greylist. Only a CVS repo at `cvs -danoncvs@anoncvs.fr.netbsd.org:/milter-greylist co`

**Comment by chris001** [comment] 2020-07-13 19:13
Ah!  OK!  Now I understand!
1. Do we know what are the email addresses of the maintainers of  the cvs repo?
2. Isn't there ways to pull request against the cvs repo, either via software commands, or by asking the cvs repo maintainers verbally by email, voice call, video call, to accept these patches ?

**Comment by chris001** [comment] 2020-07-13 19:52
See https://github.com/virtualmin/virtualmin-gpl/issues/182

**Comment by mwennrich** [comment] 2020-07-15 07:37
Sure, if you want to get it merged upstream, go ahead. The website is here: http://hcpnet.free.fr/milter-greylist/ :-) 
But "current" release of milter-greylist is from "2016-11-24 05:38" ...

**Comment by chris001** [comment] 2020-07-15 17:19
1. I sent a subscribe request to the `milter-greylist` mailing list,
2. I emailed Emmanuel on both his netbsd dot org and anime dot net email addresses, I asked him to create a github account and repo here and upload the latest `milter-greylist` code into it, so that we could then submit a github pull request with these patches/changes.  

We'll see what Emmanuel replies... stay tuned.

**Comment by chris001** [comment] 2020-07-17 20:16
I asked Emmanuel (the author of `milter-greylist`) to review and merge these changes into upstream `milter-greylist` code and make new releases for all linux distros.

This is his reply!
```
Thank you for the work on this.

I understand you removed support for the outdated format. But that means
that someone updating `milter-greylist` without GeoIP2 database will get
at broken setup, right?

What about introducing a `geoip2db` statement so that both formats can
be supported?

-- 
Emmanuel Dreyfus
```

Can we add back in the code that reads `GeoLite/GeoIP` (old version) databases also?  

So that, when users upgrade their distro `milter-greylist` packages to this new code, their setup will not immediately break because `GeoIP2` databases are not yet on their system.   

When they download the new version `GeoIP2` databases, this code will automatically use these new databases seamlessly, rather than of the older GeoLite/GeoIP databases.

Is this possible?

**Comment by mwennrich** [comment] 2020-07-28 05:34
has been merged upstream:
http://ftp.espci.fr/pub/milter-greylist/milter-greylist-4.6.3.tgz

**Closed as completed by mwennrich** 2020-07-28 05:34 UTC
